#!/usr/bin/env python
"""Regenerate blueprints/api_v1/examples.py from live API responses.

    python scripts/capture_api_examples.py

Run this whenever a response shape changes. scripts/test_api_v1.py fails when the
committed examples no longer match what the endpoints return, and this is the fix.

Each endpoint's documented example_url is fetched with every optional include=
block enabled, so the example shows the fullest shape the endpoint can produce.
Arrays are then truncated to one element and long strings to ~140 characters.
"""
import json
import pprint
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from blueprints.api_v1.catalog import ENDPOINTS, ENUMS  # noqa: E402
from blueprints.perturbseq_bp import DB_PATH  # noqa: E402

OUT = ROOT / "blueprints" / "api_v1" / "examples.py"
MAX_STR = 140
MAX_LIST = 1

HEADER = '''"""Example responses, captured from the live API and trimmed.

Generated by scripts/capture_api_examples.py rather than hand-written, so the
documented shapes match what the endpoints actually return. Arrays are truncated
to a single element and long strings to ~140 characters; everything else is
verbatim.

Do not edit by hand. scripts/test_api_v1.py asserts these keys still match live
responses, so drift fails the suite instead of quietly misleading a consumer.
"""
'''


def trim(value):
    if isinstance(value, dict):
        return {k: trim(v) for k, v in value.items()}
    if isinstance(value, list):
        return [trim(v) for v in value[:MAX_LIST]]
    if isinstance(value, str) and len(value) > MAX_STR:
        return value[:MAX_STR] + "..."
    return value


def capture_url(endpoint):
    """The URL used for an endpoint's example, with every optional block on.

    test_api_v1.py imports this so the test and the capture cannot drift apart.
    """
    url = endpoint["example_url"]
    include = next((p for p in endpoint["query_params"] if p["name"] == "include"), None)
    if include:
        url += ("&" if "?" in url else "?") + "include=" + ",".join(ENUMS[include["enum"]])
    has_per_page = any(p["name"] == "per_page" for p in endpoint["query_params"])
    if endpoint["returns"] == "collection" and has_per_page and "per_page" not in url:
        url += ("&" if "?" in url else "?") + "per_page=2"
    return url


def main():
    if not Path(DB_PATH).exists():
        print(f"DB not found at {DB_PATH}", file=sys.stderr)
        return 2

    import app as appmod

    client = appmod.app.test_client()
    captured, failed = {}, []
    for ep in ENDPOINTS:
        if ep["id"] == "index":
            continue  # self-referential; the index need not example itself
        url = capture_url(ep)
        r = client.get(url)
        if r.status_code != 200:
            failed.append(f"{ep['id']}: HTTP {r.status_code} for {url}")
            continue
        captured[ep["id"]] = trim(json.loads(r.get_data(as_text=True)))
        print(f"  {ep['id']:18s} {len(r.data):8d} -> "
              f"{len(json.dumps(captured[ep['id']])):6d} bytes")

    if failed:
        print("\nFAILED:", *failed, sep="\n  ", file=sys.stderr)
        return 1

    body = pprint.pformat(captured, width=96, sort_dicts=False)
    OUT.write_text(HEADER + "\nEXAMPLE_RESPONSES = " + body + "\n")
    print(f"\nwrote {len(captured)} examples to {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
